export default {
  apiKey: "YOUR_VALUE_ON_FIREBASE_CONSOLE",
  authDomain: "YOUR_VALUE_ON_FIREBASE_CONSOLE",
  databaseURL: "https://YOUR_VALUE_ON_FIREBASE_CONSOLE",
  projectId: "YOUR_VALUE_ON_FIREBASE_CONSOLE",
  storageBucket: "YOUR_VALUE_ON_FIREBASE_CONSOLE",
  messagingSenderId: "YOUR_VALUE_ON_FIREBASE_CONSOLE",
  appId: "YOUR_VALUE_ON_FIREBASE_CONSOLE",
  measurementId: "YOUR_VALUE_ON_FIREBASE_CONSOLE"
};